#!/usr/bin/python  
# -*- coding: utf-8 -*-  
#coding=utf-8
import win32com.client
import os, sys, string
conn = win32com.client.Dispatch('ADODB.Connection')
DSN = 'PROVIDER=Microsoft.Jet.OLEDB.4.0;DATA SOURCE=soo.mdb;Persist Security Info=False;Jet OLEDB:Database Password=123123;'
conn.Open(DSN)
print "connected"
rs = win32com.client.Dispatch('ADODB.Recordset')
sql='select * from aring where id=1'  
rs.Open('['+sql+']',conn,1,3)
rs.MoveFirst()
for x in range(rs.Fields.Count):
       print rs.Fields.Item(x).Value
conn.Close()
